name: 'Use Composite Action'

on:
  push:
    branches:
      - main

jobs:
  use_composite_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Composite Action
        uses: ashrafalih/CompositeAction@main
        with:
          example_input: 'Hello, Composite Action!'
